emailext(subject:"PASSED: Job '${env.JOB_NAME}[${env.BUILD_NUMBER}]'",
body:"Console output: ${env.BUILD_URL}console".toString(),
from:'sergei.andreev.us@gmail.com',
to:'sergei.andreev.us@gmail.com')
