node{
try {currentBuild.result="SUCCESS"
stage('File create'){build job:'AA', parameters:[string(name:'File',value: File_P)]}
stage('File modify'){build job:'BB', parameters:[string(name:'File',value: File_P)]}
stage('File delete'){build job:'CC', parameters:[string(name:'File',value: File_P)]}
}
catch(e){currentBuild.result="FAILURE"}
emailNotify()
}

def emailNotify() {
emailext(subject:"PASSED: Job '${env.JOB_NAME}[${env.BUILD_NUMBER}]'",
body:"Console output: ${env.BUILD_URL}console".toString(),
from:'sergei.andreev.us@gmail.com',
to:'sa20042004@mail.ru'
)
}
